<a href="https://colab.research.google.com/github/moonyc/pytorch-labs/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
 import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors

Creating tensors:

PyTorch's tensors are created using `torch.tensor()`

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim


3

In [16]:
TENSOR.shape
# We have one 3 by 3 shaped tensor

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

### Random tensors

Why random tensors?

Random tensors are important because neural networks learn by  starting with tensors full of random numbers and then adjusting those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3938, 0.2162, 0.3967, 0.9977],
        [0.4406, 0.9127, 0.3031, 0.0227],
        [0.5857, 0.4752, 0.3755, 0.5019]])

In [19]:
random_tensor.shape


torch.Size([3, 4])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
random_image_size_tensor

tensor([[[0.7376, 0.9771, 0.2948],
         [0.6230, 0.0906, 0.3220],
         [0.9627, 0.6623, 0.6166],
         ...,
         [0.7357, 0.9939, 0.1962],
         [0.6154, 0.7637, 0.8611],
         [0.3030, 0.1877, 0.4309]],

        [[0.8609, 0.4530, 0.8458],
         [0.4451, 0.8016, 0.3714],
         [0.2185, 0.2934, 0.2410],
         ...,
         [0.6834, 0.7336, 0.7432],
         [0.7813, 0.5149, 0.5454],
         [0.8098, 0.3021, 0.9595]],

        [[0.5629, 0.5508, 0.0902],
         [0.5661, 0.8363, 0.7260],
         [0.6964, 0.3054, 0.3685],
         ...,
         [0.7131, 0.1977, 0.5982],
         [0.1083, 0.9537, 0.5378],
         [0.3245, 0.6709, 0.4730]],

        ...,

        [[0.0653, 0.2329, 0.3043],
         [0.4398, 0.9384, 0.6765],
         [0.8449, 0.0136, 0.0228],
         ...,
         [0.9389, 0.0989, 0.4251],
         [0.1116, 0.8301, 0.8430],
         [0.2622, 0.6710, 0.0350]],

        [[0.8398, 0.8187, 0.3412],
         [0.0276, 0.4130, 0.6603],
         [0.

In [23]:
random_tensor = torch.rand(4,3)
random_tensor.shape

torch.Size([4, 3])

In [24]:
random_tensor.ndim

2

### Zeros and ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors like

In [30]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes are one of the three big errors with PyTorch and deep learning:
1. Tensors not right datatybe
2. Tensors not right shape
3. Tensors not right device

Consider float32, where the number 32 indicates the precision in computing, which measures the detail in which the quantity is expressed.

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether or not to track gradients with these tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype


torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors - tensor's attributes

Tensors not right datatybe - to get dtype from a tensor, can use tensor.dtype
Tensors not right shape - to get shape from a tensor, can use tensor.shape
Tensors not right device - to get device from a tensor, can use tensor.device

In [38]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4761, 0.1451, 0.6435, 0.8621],
        [0.4983, 0.7008, 0.4273, 0.5414],
        [0.8674, 0.7965, 0.4293, 0.6689]])

In [39]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4761, 0.1451, 0.6435, 0.8621],
        [0.4983, 0.7008, 0.4273, 0.5414],
        [0.8674, 0.7965, 0.4293, 0.6689]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor's operations)

Tensor's operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [42]:
# Subtract 10
tensor - 10


tensor([-9, -8, -7])

In [43]:
# Try out Pytorch in-built functions
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [45]:
secondTensor = torch.tensor([0,1,2])
secondTensor

tensor([0, 1, 2])

In [46]:
tensor * secondTensor

tensor([0, 2, 6])

# Matrix multiplication

We know two main ways of performing multiplications in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ ()2, 3` -> `(3, 3)`

In [62]:
torch.matmul(torch.rand(5, 1), torch.rand(1, 5)).shape

torch.Size([5, 5])

In [53]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [52]:
tensor @ tensor

tensor(14)

In [50]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 480 µs, total: 480 µs
Wall time: 5.24 ms


tensor(14)

In [51]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 11 µs, total: 77 µs
Wall time: 81.1 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [82]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],[3, 4],[5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [8, 1]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  10],
        [ 61,  68,  28],
        [ 95, 106,  46]])

In [68]:
tensor_A.shape

torch.Size([3, 2])

In [71]:
tensor_B.shape

torch.Size([2, 3])

To fix the shape of our tensors, we can manipulate the shape of one of our tensors, using **Transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [76]:
tensor_B, tensor_B.shape


(tensor([[ 7, 10],
         [ 8, 11],
         [ 8,  1]]),
 torch.Size([3, 2]))

In [80]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  8],
         [10, 11,  1]]),
 torch.Size([2, 3]))

In [87]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  10],
        [ 61,  68,  28],
        [ 95, 106,  46]])

Output shape: torch.Size([3, 3])
