<a href="https://colab.research.google.com/github/moonyc/pytorch-labs/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [102]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


In [103]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors

Creating tensors:

PyTorch's tensors are created using `torch.tensor()`

In [104]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [105]:
scalar.ndim

0

In [106]:
# Get tensor back as Python int
scalar.item()

7

In [107]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [108]:
vector.ndim

1

In [109]:
vector.shape

torch.Size([2])

In [110]:
# Matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [111]:
MATRIX.ndim

2

In [112]:
MATRIX[0]

tensor([7, 8])

In [113]:
MATRIX[1]

tensor([ 9, 10])

In [114]:
MATRIX.shape

torch.Size([2, 2])

In [115]:
# Tensor
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [116]:
TENSOR.ndim


3

In [117]:
TENSOR.shape
# We have one 3 by 3 shaped tensor

torch.Size([1, 3, 3])

In [118]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

### Random tensors

Why random tensors?

Random tensors are important because neural networks learn by  starting with tensors full of random numbers and then adjusting those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [119]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2695, 0.4162, 0.2027, 0.2119],
        [0.2121, 0.3693, 0.2586, 0.7476],
        [0.5191, 0.1068, 0.1157, 0.8181]])

In [120]:
random_tensor.shape


torch.Size([3, 4])

In [121]:
random_tensor.ndim

2

In [122]:
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [123]:
random_image_size_tensor

tensor([[[0.8523, 0.1049, 0.1229],
         [0.9921, 0.8416, 0.9428],
         [0.8492, 0.2194, 0.3419],
         ...,
         [0.5880, 0.0304, 0.5977],
         [0.3691, 0.9250, 0.2579],
         [0.9342, 0.6415, 0.9919]],

        [[0.5888, 0.1737, 0.8336],
         [0.7840, 0.8225, 0.7450],
         [0.0449, 0.3217, 0.7319],
         ...,
         [0.9965, 0.6057, 0.7868],
         [0.9412, 0.9206, 0.0578],
         [0.7043, 0.3069, 0.1955]],

        [[0.3818, 0.4484, 0.1508],
         [0.3397, 0.0379, 0.3872],
         [0.0714, 0.4863, 0.7916],
         ...,
         [0.6560, 0.4270, 0.7233],
         [0.1352, 0.7521, 0.4242],
         [0.8448, 0.5544, 0.5086]],

        ...,

        [[0.8446, 0.9067, 0.7820],
         [0.5658, 0.4875, 0.5515],
         [0.5798, 0.7917, 0.0478],
         ...,
         [0.9957, 0.1501, 0.5895],
         [0.7110, 0.4027, 0.6870],
         [0.6462, 0.7618, 0.4895]],

        [[0.6198, 0.2259, 0.4831],
         [0.8233, 0.1642, 0.2954],
         [0.

In [124]:
random_tensor = torch.rand(4,3)
random_tensor.shape

torch.Size([4, 3])

In [125]:
random_tensor.ndim

2

### Zeros and ones

In [126]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [127]:
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [128]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [129]:
ones.dtype

torch.float32

In [130]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors like

In [131]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [132]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes are one of the three big errors with PyTorch and deep learning:
1. Tensors not right datatybe
2. Tensors not right shape
3. Tensors not right device

Consider float32, where the number 32 indicates the precision in computing, which measures the detail in which the quantity is expressed.

In [133]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether or not to track gradients with these tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [134]:
float_32_tensor.dtype


torch.float32

In [135]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [136]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [137]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [138]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors - tensor's attributes

Tensors not right datatybe - to get dtype from a tensor, can use tensor.dtype
Tensors not right shape - to get shape from a tensor, can use tensor.shape
Tensors not right device - to get device from a tensor, can use tensor.device

In [139]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9922, 0.0989, 0.1228, 0.8675],
        [0.3023, 0.7907, 0.0865, 0.4350],
        [0.7319, 0.5887, 0.8846, 0.0057]])

In [140]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9922, 0.0989, 0.1228, 0.8675],
        [0.3023, 0.7907, 0.0865, 0.4350],
        [0.7319, 0.5887, 0.8846, 0.0057]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor's operations)

Tensor's operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [141]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [142]:
# Multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [143]:
# Subtract 10
tensor - 10


tensor([-9, -8, -7])

In [144]:
# Try out Pytorch in-built functions
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [145]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [146]:
secondTensor = torch.tensor([0,1,2])
secondTensor

tensor([0, 1, 2])

In [147]:
tensor * secondTensor

tensor([0, 2, 6])

# Matrix multiplication

We know two main ways of performing multiplications in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ ()2, 3` -> `(3, 3)`

In [148]:
torch.matmul(torch.rand(5, 1), torch.rand(1, 5)).shape

torch.Size([5, 5])

In [149]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [150]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [151]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [152]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [153]:
tensor @ tensor

tensor(14)

In [154]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 173 µs, sys: 945 µs, total: 1.12 ms
Wall time: 909 µs


tensor(14)

In [155]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 387 µs, sys: 52 µs, total: 439 µs
Wall time: 383 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [156]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],[3, 4],[5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [8, 1]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  10],
        [ 61,  68,  28],
        [ 95, 106,  46]])

In [157]:
tensor_A.shape

torch.Size([3, 2])

In [158]:
tensor_B.shape

torch.Size([3, 2])

To fix the shape of our tensors, we can manipulate the shape of one of our tensors, using **Transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [159]:
tensor_B, tensor_B.shape


(tensor([[ 7, 10],
         [ 8, 11],
         [ 8,  1]]),
 torch.Size([3, 2]))

In [160]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  8],
         [10, 11,  1]]),
 torch.Size([2, 3]))

In [161]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  10],
        [ 61,  68,  28],
        [ 95, 106,  46]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [162]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [163]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [164]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [165]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [166]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Find the positional min and max



In [167]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [168]:
# Find the position in tensor that has the minimum value with argmin() -> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [169]:
x[0]

tensor(0)

In [170]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [171]:
x[9]

tensor(90)

  ## Reshaping, stacking, squeezing and unsqueezing tensors

  * Reshaping - reshapes an input tensor to a defined shape
  * View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
  * Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
  * Squeexe - removes all `1` dimensions from a tensor
  * Unsqueeze - add a `1` dimension to a target tensor
  * Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [172]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [173]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [174]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [175]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [176]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [177]:
# torch.squeeze() - removes all single dimension from a target
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [178]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [179]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=( 224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channel, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [180]:
x_original[:, :, 0]

tensor([[0.9300, 0.3741, 0.7578,  ..., 0.2466, 0.7769, 0.8114],
        [0.7520, 0.9223, 0.6984,  ..., 0.2963, 0.7421, 0.4373],
        [0.2511, 0.1015, 0.9672,  ..., 0.5276, 0.1819, 0.7523],
        ...,
        [0.1144, 0.6118, 0.0450,  ..., 0.1448, 0.6066, 0.6541],
        [0.2701, 0.1490, 0.5107,  ..., 0.0206, 0.5245, 0.3607],
        [0.9339, 0.1699, 0.3475,  ..., 0.5478, 0.6283, 0.4194]])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [181]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [182]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [183]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [184]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [185]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [186]:
# Get all values of 0th and 1st dimensions but only index 1 and 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [187]:
# Get all values of the 0 dimension but only the index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [188]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [189]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [190]:
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [191]:
x[0,2,2]

tensor(9)

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.
Pytorch has functionality to interact with it.

* Data in NumPy to PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor to NumPy -> `torch.Tensor.numpy()`


In [192]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [193]:
array.dtype

dtype('float64')

dtype('float64')

In [194]:
tensor.dtype

torch.float64

torch.float64

In [195]:
torch.arange(1.0, 8.0).dtype

torch.float32